PushRelabel: NodePool Class Reference
NodePool Class Reference
#include <NodePool.h>
Public Member Functions
virtual void addNode (Node *node)=0
virtual Node * getNode ()=0
int getCount ()
void incCount ()
int isEmpty ()
Protected Attributes
int count
Detailed Description
Definition at line 5 of file NodePool.h.
Member Function Documentation
virtual void NodePool::addNode (Node * node) [pure virtual]
Implemented in FifoQueue, HighLabelQueue, and PriorityQueue.
Referenced by PushRelabel::calc(), PushRelabel::discharge(), and PushRelabel::discharge_back().
virtual Node* NodePool::getNode () [pure virtual]
Implemented in DijkstraQueue, FifoQueue, HighLabelQueue, and PriorityQueue.
Referenced by PushRelabel::flow(), and PushRelabel::preflow().
int NodePool::getCount () [inline]
Definition at line 10 of file NodePool.h.
References count.
void NodePool::incCount () [inline]
Definition at line 11 of file NodePool.h.
References count.
int NodePool::isEmpty () [inline]
Definition at line 12 of file NodePool.h.
References count.
Referenced by PushRelabel::calc(), Graph::dijkstra(), PushRelabel::flow(), and PushRelabel::preflow().
Member Data Documentation
int NodePool::count [protected]
Definition at line 14 of file NodePool.h.
Referenced by PriorityQueue::addNode(), HighLabelQueue::addNode(), FifoQueue::addNode(), DijkstraQueue::addNode(), FifoQueue::FifoQueue(), getCount(), PriorityQueue::getNode(), HighLabelQueue::getNode(), FifoQueue::getNode(), DijkstraQueue::getNode(), HighLabelQueue::HighLabelQueue(), incCount(), and isEmpty().
The documentation for this class was generated from the following file:
C:/Users/Nimrod/Documents/University/2007 - Semester 1/Algorithm Workshop/Project/NodePool.h