PushRelabel: Node Class Reference
Node Class Reference
#include <Node.h>
Public Member Functions
Node ()
bool operator> (const Node *node) const
bool operator< (const Node *node) const
int getDegree ()
void setDegree (int deg)
int getLabel ()
void setLabel (int lab)
int getExcess ()
void setExcess (int exc)
void incExcess (int value)
void decExcess (int value)
int getID ()
void setID (int node_id)
EdgeEntry * getAdjList ()
EdgeEntry * getLastEdge ()
void incNumEdges ()
int getNumEdges ()
void addEdge (EdgeEntry *edge)
void printNode ()
void debugNodeDump ()
Private Attributes
int degree
int label
int excess
int id
int numEdges
EdgeEntry * adjList
EdgeEntry * lastEdge
Detailed Description
Definition at line 13 of file Node.h.
Constructor & Destructor Documentation
Node::Node ()
Definition at line 15 of file Node.cpp.
References adjList, degree, excess, label, lastEdge, and numEdges.
Member Function Documentation
bool Node::operator> (const Node * node) const
Definition at line 58 of file Node.cpp.
References label.
bool Node::operator< (const Node * node) const
Definition at line 63 of file Node.cpp.
References label.
int Node::getDegree () [inline]
Definition at line 20 of file Node.h.
References degree.
Referenced by debugNodeDump().
void Node::setDegree (int deg) [inline]
Definition at line 21 of file Node.h.
References degree.
int Node::getLabel () [inline]
Definition at line 22 of file Node.h.
References label.
Referenced by HighLabelQueue::addNode(), PushRelabel::calc(), debugNodeDump(), PushRelabel::discharge(), PushRelabel::discharge_back(), PushRelabel::findClosestPushBack(), PushRelabel::findLowestLabelEdge(), PushRelabel::isAdmissible(), and PushRelabel::updateLabels().
void Node::setLabel (int lab) [inline]
Definition at line 23 of file Node.h.
References label.
Referenced by PushRelabel::discharge(), PushRelabel::discharge_back(), and PushRelabel::updateLabels().
int Node::getExcess () [inline]
Definition at line 24 of file Node.h.
References excess.
Referenced by PushRelabel::calc(), debugNodeDump(), PushRelabel::dijkstraPath(), PushRelabel::discharge(), PushRelabel::discharge_back(), and PushRelabel::push().
void Node::setExcess (int exc) [inline]
Definition at line 25 of file Node.h.
References excess.
Referenced by PushRelabel::calc(), and PushRelabel::discharge_back().
void Node::incExcess (int value) [inline]
Definition at line 26 of file Node.h.
References excess.
Referenced by PushRelabel::discharge_back(), and PushRelabel::push().
void Node::decExcess (int value)
Definition at line 27 of file Node.cpp.
References excess.
Referenced by PushRelabel::discharge_back(), and PushRelabel::push().
int Node::getID () [inline]
Definition at line 28 of file Node.h.
References id.
Referenced by debugNodeDump(), Graph::dijkstra(), PushRelabel::discharge(), PushRelabel::discharge_back(), DijkstraQueue::getNode(), and PushRelabel::push().
void Node::setID (int node_id) [inline]
Definition at line 29 of file Node.h.
EdgeEntry* Node::getAdjList () [inline]
Definition at line 30 of file Node.h.
References adjList.
Referenced by Graph::dijkstra(), PushRelabel::dijkstraPath(), PushRelabel::discharge(), PushRelabel::discharge_back(), PushRelabel::findClosestPushBack(), PushRelabel::findLowestLabelEdge(), Graph::incPrevPathCap(), and PushRelabel::updateLabels().
EdgeEntry* Node::getLastEdge () [inline]
Definition at line 31 of file Node.h.
References lastEdge.
void Node::incNumEdges () [inline]
Definition at line 32 of file Node.h.
References numEdges.
int Node::getNumEdges () [inline]
Definition at line 33 of file Node.h.
References numEdges.
void Node::addEdge (EdgeEntry * edge)
Definition at line 5 of file Node.cpp.
References lastEdge, EdgeEntry::nextEdge, numEdges, and EdgeEntry::prevEdge.
Referenced by Graph::readGraph().
void Node::printNode ()
Definition at line 36 of file Node.cpp.
References adjList, EdgeEntry::getCapacity(), EdgeEntry::getEndPoint(), and EdgeEntry::getNext().
Referenced by Graph::printGraph().
void Node::debugNodeDump ()
Definition at line 48 of file Node.cpp.
References getDegree(), getExcess(), getID(), getLabel(), and Utils::printValue().
Referenced by Graph::debugDump().
Member Data Documentation
int Node::degree [private]
Definition at line 40 of file Node.h.
Referenced by getDegree(), Node(), and setDegree().
int Node::label [private]
Definition at line 41 of file Node.h.
Referenced by getLabel(), Node(), operator<(), operator>(), and setLabel().
int Node::excess [private]
Definition at line 42 of file Node.h.
Referenced by decExcess(), getExcess(), incExcess(), Node(), and setExcess().
int Node::id [private]
Definition at line 43 of file Node.h.
Referenced by getID().
int Node::numEdges [private]
Definition at line 44 of file Node.h.
Referenced by addEdge(), getNumEdges(), incNumEdges(), and Node().
EdgeEntry* Node::adjList [private]
Definition at line 46 of file Node.h.
Referenced by getAdjList(), Node(), and printNode().
EdgeEntry* Node::lastEdge [private]
Definition at line 47 of file Node.h.
Referenced by addEdge(), getLastEdge(), and Node().
The documentation for this class was generated from the following files:
C:/Users/Nimrod/Documents/University/2007 - Semester 1/Algorithm Workshop/Project/Node.h
C:/Users/Nimrod/Documents/University/2007 - Semester 1/Algorithm Workshop/Project/Node.cpp