PushRelabel: PushRelabel Class Reference
PushRelabel Class Reference
#include <PushRelabel.h>
Public Member Functions
PushRelabel (void)
~PushRelabel (void)
Static Public Member Functions
static int calc (Graph *g)
static EdgeEntry * findLowestLabelEdge (Node *node)
static int dijkstraPath ()
Static Public Attributes
static unsigned long numOfPushes
static unsigned long numOfRelabels
static int dist
Static Private Member Functions
static int updateLabels (bool fromTarget, bool calcPrev)
static int preflow ()
static int flow ()
static int discharge (Node *node)
static int discharge_back (Node *node)
static int findClosestPushBack (Node *node)
static bool isAdmissible (Node *start, EdgeEntry *edge)
static int push (int start, EdgeEntry *edge, int value)
Static Private Attributes
static Graph * g
static Node * nodeArr
Detailed Description
Definition at line 8 of file PushRelabel.h.
Constructor & Destructor Documentation
PushRelabel::PushRelabel (void)
PushRelabel::~PushRelabel (void)
Member Function Documentation
int PushRelabel::calc (Graph * g) [static]
Definition at line 21 of file PushRelabel.cpp.
References NodePool::addNode(), DEBUG, Graph::debugDump(), dist, flow(), g, Node::getExcess(), Node::getLabel(), Graph::getNodeArray(), Graph::getNodesNum(), Graph::getPool(), Graph::getSource(), Graph::getTarget(), INFINITY, NodePool::isEmpty(), LOG_2, LOG_3, LOG_NONE, nodeArr, numOfPushes, numOfRelabels, preflow(), Graph::printGraph(), Node::setExcess(), and updateLabels().
Referenced by main().
EdgeEntry * PushRelabel::findLowestLabelEdge (Node * node) [static]
Definition at line 410 of file PushRelabel.cpp.
References Node::getAdjList(), EdgeEntry::getEndPoint(), Node::getLabel(), EdgeEntry::getNext(), EdgeEntry::getResCapacity(), INFINITY, and nodeArr.
Referenced by discharge().
int PushRelabel::dijkstraPath (void) [static]
Definition at line 430 of file PushRelabel.cpp.
References Graph::dijkstra(), dist, g, Node::getAdjList(), EdgeEntry::getEndPoint(), Node::getExcess(), EdgeEntry::getNext(), Graph::getNodesNum(), Graph::getSource(), Graph::getTarget(), INFINITY, nodeArr, and push().
Referenced by main().
int PushRelabel::updateLabels (bool fromTarget, bool calcPrev) [static, private]
Definition at line 93 of file PushRelabel.cpp.
References DEBUG, g, Node::getAdjList(), EdgeEntry::getEndPoint(), Node::getLabel(), EdgeEntry::getNext(), Graph::getNodesNum(), Graph::getSource(), Graph::getTarget(), LEVEL_UP, LOG_2, LOG_3, NEW_NODE, nodeArr, Graph::prevArray, EdgeEntry::push(), QUEUE_NODE, Node::setLabel(), and Graph::setMaxDistance().
Referenced by calc(), discharge(), and discharge_back().
int PushRelabel::preflow () [static, private]
Definition at line 180 of file PushRelabel.cpp.
References discharge(), g, NodePool::getNode(), Graph::getPool(), and NodePool::isEmpty().
Referenced by calc().
int PushRelabel::flow () [static, private]
Definition at line 296 of file PushRelabel.cpp.
References DEBUG, discharge_back(), g, NodePool::getNode(), Graph::getNodesNum(), Graph::getPool(), NodePool::isEmpty(), LOG_2, and nodeArr.
Referenced by calc().
int PushRelabel::discharge (Node * node) [static, private]
Definition at line 192 of file PushRelabel.cpp.
References NodePool::addNode(), dist, findLowestLabelEdge(), g, Node::getAdjList(), EdgeEntry::getEndPoint(), Node::getExcess(), Node::getID(), Node::getLabel(), EdgeEntry::getNext(), Graph::getPool(), EdgeEntry::getResCapacity(), Graph::getSource(), Graph::getTarget(), INFINITY, isAdmissible(), nodeArr, numOfRelabels, push(), Node::setLabel(), and updateLabels().
Referenced by preflow().
int PushRelabel::discharge_back (Node * node) [static, private]
Definition at line 323 of file PushRelabel.cpp.
References NodePool::addNode(), Node::decExcess(), dist, findClosestPushBack(), g, Node::getAdjList(), EdgeEntry::getCapacity(), EdgeEntry::getEndPoint(), Node::getExcess(), EdgeEntry::getFlow(), Node::getID(), Node::getLabel(), EdgeEntry::getNext(), Graph::getPool(), Graph::getSource(), Node::incExcess(), INFINITY, nodeArr, EdgeEntry::push(), Node::setExcess(), Node::setLabel(), and updateLabels().
Referenced by flow().
int PushRelabel::findClosestPushBack (Node * node) [static, private]
Definition at line 388 of file PushRelabel.cpp.
References Node::getAdjList(), EdgeEntry::getCapacity(), EdgeEntry::getEndPoint(), EdgeEntry::getFlow(), Node::getLabel(), EdgeEntry::getNext(), INFINITY, EdgeEntry::isReverseEdge(), and nodeArr.
Referenced by discharge_back().
bool PushRelabel::isAdmissible (Node * start, EdgeEntry * edge) [static, private]
Definition at line 267 of file PushRelabel.cpp.
References EdgeEntry::getEndPoint(), Node::getLabel(), EdgeEntry::isSaturated(), and nodeArr.
Referenced by discharge().
int PushRelabel::push (int start, EdgeEntry * edge, int value) [static, private]
Definition at line 274 of file PushRelabel.cpp.
References DEBUG, Node::decExcess(), EdgeEntry::getEndPoint(), Node::getExcess(), Node::getID(), Node::incExcess(), LOG_2, nodeArr, numOfPushes, Utils::printValue(), and EdgeEntry::push().
Referenced by dijkstraPath(), and discharge().
Member Data Documentation
unsigned long PushRelabel::numOfPushes [static]
Definition at line 18 of file PushRelabel.h.
Referenced by calc(), and push().
unsigned long PushRelabel::numOfRelabels [static]
Definition at line 19 of file PushRelabel.h.
Referenced by calc(), and discharge().
int PushRelabel::dist [static]
Definition at line 20 of file PushRelabel.h.
Referenced by calc(), dijkstraPath(), discharge(), and discharge_back().
Graph * PushRelabel::g [static, private]
Definition at line 25 of file PushRelabel.h.
Referenced by calc(), dijkstraPath(), discharge(), discharge_back(), flow(), preflow(), and updateLabels().
Node * PushRelabel::nodeArr [static, private]
Definition at line 26 of file PushRelabel.h.
Referenced by calc(), dijkstraPath(), discharge(), discharge_back(), findClosestPushBack(), findLowestLabelEdge(), flow(), isAdmissible(), push(), and updateLabels().
The documentation for this class was generated from the following files:
C:/Users/Nimrod/Documents/University/2007 - Semester 1/Algorithm Workshop/Project/PushRelabel.h
C:/Users/Nimrod/Documents/University/2007 - Semester 1/Algorithm Workshop/Project/PushRelabel.cpp