PushRelabel: DijkstraQueue Class Reference
DijkstraQueue Class Reference
#include <DijkstraQueue.h>
Public Member Functions
DijkstraQueue (int node_num)
~DijkstraQueue (void)
void findNewPtr ()
void addNode (Node *node, int distance)
Node * getNode ()
Node * getNode (int ptr, int id)
Private Attributes
int arrayPtr
Detailed Description
Definition at line 8 of file DijkstraQueue.h.
Constructor & Destructor Documentation
DijkstraQueue::DijkstraQueue (int node_num)
Definition at line 4 of file DijkstraQueue.cpp.
References arrayPtr, and HighLabelQueue::listArray.
DijkstraQueue::~DijkstraQueue (void)
Definition at line 11 of file DijkstraQueue.cpp.
References HighLabelQueue::listArray.
Member Function Documentation
void DijkstraQueue::findNewPtr ()
Reimplemented from HighLabelQueue.
Definition at line 56 of file DijkstraQueue.cpp.
References arrayPtr, and HighLabelQueue::listArray.
Referenced by getNode().
void DijkstraQueue::addNode (Node * node, int distance)
Definition at line 17 of file DijkstraQueue.cpp.
References arrayPtr, NodePool::count, HighLabelQueue::DList::insertFront(), and HighLabelQueue::listArray.
Referenced by Graph::dijkstra().
Node * DijkstraQueue::getNode () [virtual]
Reimplemented from HighLabelQueue.
Definition at line 26 of file DijkstraQueue.cpp.
References arrayPtr, NodePool::count, findNewPtr(), HighLabelQueue::listArray, and HighLabelQueue::DList::removeFront().
Referenced by Graph::dijkstra().
Node * DijkstraQueue::getNode (int ptr, int id)
Definition at line 37 of file DijkstraQueue.cpp.
References NodePool::count, findNewPtr(), Node::getID(), HighLabelQueue::DList::insertBack(), HighLabelQueue::listArray, and HighLabelQueue::DList::removeFront().
Member Data Documentation
int DijkstraQueue::arrayPtr [private]
Reimplemented from HighLabelQueue.
Definition at line 21 of file DijkstraQueue.h.
Referenced by addNode(), DijkstraQueue(), findNewPtr(), and getNode().
The documentation for this class was generated from the following files:
C:/Users/Nimrod/Documents/University/2007 - Semester 1/Algorithm Workshop/Project/DijkstraQueue.h
C:/Users/Nimrod/Documents/University/2007 - Semester 1/Algorithm Workshop/Project/DijkstraQueue.cpp