PushRelabel: EdgeEntry Class Reference
EdgeEntry Class Reference
#include <EdgeEntry.h>
Public Member Functions
void push (int value)
int getEndPoint ()
int getCapacity ()
void incCapacity (int value)
void incFlow (signed int value)
int getFlow ()
bool isSaturated ()
int getResCapacity ()
EdgeEntry * getNext ()
EdgeEntry * getPrev ()
EdgeEntry * getReverse ()
void setReversed (EdgeEntry *other)
bool isReverseEdge ()
EdgeEntry (int end, int cap, int flow, EdgeEntry *prev)
Public Attributes
EdgeEntry * nextEdge
EdgeEntry * prevEdge
Private Attributes
int endPoint
int capacity
signed int flow
EdgeEntry * reverseEdge
Detailed Description
Definition at line 13 of file EdgeEntry.h.
Constructor & Destructor Documentation
EdgeEntry::EdgeEntry (int end, int cap, int flow, EdgeEntry * prev)
Definition at line 4 of file EdgeEntry.cpp.
References capacity, endPoint, flow, nextEdge, prevEdge, and reverseEdge.
Member Function Documentation
void EdgeEntry::push (int value)
Definition at line 15 of file EdgeEntry.cpp.
References flow, incFlow(), and reverseEdge.
Referenced by PushRelabel::discharge_back(), PushRelabel::push(), and PushRelabel::updateLabels().
int EdgeEntry::getEndPoint () [inline]
Definition at line 18 of file EdgeEntry.h.
References endPoint.
Referenced by Graph::dijkstra(), PushRelabel::dijkstraPath(), PushRelabel::discharge(), PushRelabel::discharge_back(), PushRelabel::findClosestPushBack(), PushRelabel::findLowestLabelEdge(), Graph::incPrevPathCap(), PushRelabel::isAdmissible(), isReverseEdge(), Node::printNode(), PushRelabel::push(), and PushRelabel::updateLabels().
int EdgeEntry::getCapacity () [inline]
Definition at line 19 of file EdgeEntry.h.
References capacity.
Referenced by PushRelabel::discharge_back(), PushRelabel::findClosestPushBack(), and Node::printNode().
void EdgeEntry::incCapacity (int value) [inline]
Definition at line 20 of file EdgeEntry.h.
References capacity.
Referenced by Graph::incPrevPathCap().
void EdgeEntry::incFlow (signed int value) [inline]
Definition at line 21 of file EdgeEntry.h.
References flow.
Referenced by push().
int EdgeEntry::getFlow () [inline]
Definition at line 22 of file EdgeEntry.h.
References flow.
Referenced by Graph::dijkstra(), PushRelabel::discharge_back(), and PushRelabel::findClosestPushBack().
bool EdgeEntry::isSaturated () [inline]
Definition at line 23 of file EdgeEntry.h.
References capacity, and flow.
Referenced by PushRelabel::isAdmissible().
int EdgeEntry::getResCapacity () [inline]
Definition at line 24 of file EdgeEntry.h.
References capacity, and flow.
Referenced by Graph::dijkstra(), PushRelabel::discharge(), and PushRelabel::findLowestLabelEdge().
EdgeEntry* EdgeEntry::getNext () [inline]
Definition at line 26 of file EdgeEntry.h.
References nextEdge.
Referenced by Graph::dijkstra(), PushRelabel::dijkstraPath(), PushRelabel::discharge(), PushRelabel::discharge_back(), PushRelabel::findClosestPushBack(), PushRelabel::findLowestLabelEdge(), Graph::incPrevPathCap(), Node::printNode(), and PushRelabel::updateLabels().
EdgeEntry* EdgeEntry::getPrev () [inline]
Definition at line 27 of file EdgeEntry.h.
References prevEdge.
EdgeEntry* EdgeEntry::getReverse () [inline]
Definition at line 28 of file EdgeEntry.h.
References reverseEdge.
Referenced by Graph::incPrevPathCap().
void EdgeEntry::setReversed (EdgeEntry * other)
Definition at line 22 of file EdgeEntry.cpp.
References reverseEdge.
Referenced by Graph::readGraph().
bool EdgeEntry::isReverseEdge ()
Definition at line 28 of file EdgeEntry.cpp.
References endPoint, getEndPoint(), and reverseEdge.
Referenced by Graph::dijkstra(), and PushRelabel::findClosestPushBack().
Member Data Documentation
EdgeEntry* EdgeEntry::nextEdge
Definition at line 34 of file EdgeEntry.h.
Referenced by Node::addEdge(), EdgeEntry(), and getNext().
EdgeEntry* EdgeEntry::prevEdge
Definition at line 35 of file EdgeEntry.h.
Referenced by Node::addEdge(), EdgeEntry(), and getPrev().
int EdgeEntry::endPoint [private]
Definition at line 38 of file EdgeEntry.h.
Referenced by EdgeEntry(), getEndPoint(), and isReverseEdge().
int EdgeEntry::capacity [private]
Definition at line 39 of file EdgeEntry.h.
Referenced by EdgeEntry(), getCapacity(), getResCapacity(), incCapacity(), and isSaturated().
signed int EdgeEntry::flow [private]
Definition at line 40 of file EdgeEntry.h.
Referenced by EdgeEntry(), getFlow(), getResCapacity(), incFlow(), isSaturated(), and push().
EdgeEntry* EdgeEntry::reverseEdge [private]
Definition at line 41 of file EdgeEntry.h.
Referenced by EdgeEntry(), getReverse(), isReverseEdge(), push(), and setReversed().
The documentation for this class was generated from the following files:
C:/Users/Nimrod/Documents/University/2007 - Semester 1/Algorithm Workshop/Project/EdgeEntry.h
C:/Users/Nimrod/Documents/University/2007 - Semester 1/Algorithm Workshop/Project/EdgeEntry.cpp