PushRelabel: C:/Users/Nimrod/Documents/University/2007 - Semester 1/Algorithm Workshop/Project/glib.c File Reference
C:/Users/Nimrod/Documents/University/2007 - Semester 1/Algorithm Workshop/Project/glib.c File Reference
#include "graphtypes.h"
#include <stdio.h>
#include <math.h>
Functions
AddEdge (Graph g, int n, int m, int label)
Edge FindEdge (Graph graph, int i, int j)
int RemoveEdge (Graph graph, Edge edge)
int NumEdges (Graph g)
Graph NewGraph (int size)
EuclidGraph NewEuclid (int size)
MatrixGraph NewMatrix (int size)
Graph CopyGraph (Graph g)
Graph ReadGraph (int *size, file)
WriteGraph (Graph graph, file)
EuclidGraph ReadEuclid (int *size, file)
WriteEuclid (EuclidGraph graph, file)
MatrixGraph ReadMatrix (int *size, file)
WriteMatrix (MatrixGraph graph, file)
int eucdist (EuclidGraph graph, int i, int j)
int eucdist2 (EuclidGraph graph, int i, int j)
int eucdistsq (EuclidGraph graph, int i, int j)
Function Documentation
AddEdge (Graph g, int n, int m, int label)
Definition at line 9 of file glib.c.
Referenced by CopyGraph(), and ReadGraph().
Graph CopyGraph (Graph g)
Definition at line 144 of file glib.c.
References AddEdge(), and NewGraph().
int eucdist (EuclidGraph graph, int i, int j)
Definition at line 361 of file glib.c.
int eucdist2 (EuclidGraph graph, int i, int j)
Definition at line 383 of file glib.c.
int eucdistsq (EuclidGraph graph, int i, int j)
Definition at line 398 of file glib.c.
Edge FindEdge (Graph graph, int i, int j)
Definition at line 39 of file glib.c.
EuclidGraph NewEuclid (int size)
Definition at line 119 of file glib.c.
Referenced by ReadEuclid().
Graph NewGraph (int size)
Definition at line 102 of file glib.c.
Referenced by CopyGraph(), and ReadGraph().
MatrixGraph NewMatrix (int size)
Definition at line 129 of file glib.c.
Referenced by ReadMatrix().
int NumEdges (Graph g)
Definition at line 90 of file glib.c.
Referenced by WriteGraph().
EuclidGraph ReadEuclid (int * size, file)
Definition at line 245 of file glib.c.
References NewEuclid().
Graph ReadGraph (int * size, file)
Definition at line 167 of file glib.c.
References AddEdge(), and NewGraph().
MatrixGraph ReadMatrix (int * size, file)
Definition at line 300 of file glib.c.
References NewMatrix().
int RemoveEdge (Graph graph, Edge edge)
Definition at line 52 of file glib.c.
WriteEuclid (EuclidGraph graph, file)
Definition at line 280 of file glib.c.
WriteGraph (Graph graph, file)
Definition at line 215 of file glib.c.
References NumEdges().
WriteMatrix (MatrixGraph graph, file)
Definition at line 336 of file glib.c.