PushRelabel: HighLabelQueue::DList Class Reference
HighLabelQueue::DList Class Reference
#include <HighLabelQueue.h>
Public Member Functions
DList ()
void insertFront (Node *node)
void insertBack (Node *node)
Node * removeFront ()
void insertBefore (Node *node, ListNode *nodeB)
Public Attributes
ListNode * front
ListNode * back
Detailed Description
Definition at line 25 of file HighLabelQueue.h.
Constructor & Destructor Documentation
HighLabelQueue::DList::DList () [inline]
Definition at line 31 of file HighLabelQueue.h.
References back, and front.
Member Function Documentation
void HighLabelQueue::DList::insertFront (Node * node)
Definition at line 68 of file HighLabelQueue.cpp.
References back, front, HighLabelQueue::ListNode::next, HighLabelQueue::ListNode::node, and HighLabelQueue::ListNode::prev.
Referenced by HighLabelQueue::addNode(), and DijkstraQueue::addNode().
void HighLabelQueue::DList::insertBack (Node * node)
Definition at line 93 of file HighLabelQueue.cpp.
References back, front, HighLabelQueue::ListNode::next, HighLabelQueue::ListNode::node, and HighLabelQueue::ListNode::prev.
Referenced by DijkstraQueue::getNode().
Node * HighLabelQueue::DList::removeFront ()
Definition at line 118 of file HighLabelQueue.cpp.
References back, front, HighLabelQueue::ListNode::next, HighLabelQueue::ListNode::node, and HighLabelQueue::ListNode::prev.
Referenced by HighLabelQueue::getNode(), and DijkstraQueue::getNode().
void HighLabelQueue::DList::insertBefore (Node * node, ListNode * nodeB)
Member Data Documentation
ListNode* HighLabelQueue::DList::front
Definition at line 28 of file HighLabelQueue.h.
Referenced by DList(), insertBack(), insertFront(), and removeFront().
ListNode* HighLabelQueue::DList::back
Definition at line 29 of file HighLabelQueue.h.
Referenced by DList(), insertBack(), insertFront(), and removeFront().
The documentation for this class was generated from the following files:
C:/Users/Nimrod/Documents/University/2007 - Semester 1/Algorithm Workshop/Project/HighLabelQueue.h
C:/Users/Nimrod/Documents/University/2007 - Semester 1/Algorithm Workshop/Project/HighLabelQueue.cpp