PushRelabel: Graph Class Reference
Graph Class Reference
#include <Graph.h>
Public Member Functions
Graph (string file)
~Graph (void)
int getSource ()
int getTarget ()
int getNodesNum ()
int getEdgesNum ()
int getMaxDistance ()
void setMaxDistance (int max)
NodePool * getPool ()
int readGraph (string file)
int printGraph ()
int debugDump ()
Node * getNodeArray ()
int dijkstra (int source_id, int *&dist, int *&prev, int &max)
int incPrevPathCap (int val)
Public Attributes
int * prevArray
Private Attributes
int sourceID
int targetID
int nodesNum
int edgesNum
int maxDistance
NodePool * pool
Node * nodeArray
Detailed Description
Definition at line 12 of file Graph.h.
Constructor & Destructor Documentation
Graph::Graph (string file)
Definition at line 6 of file Graph.cpp.
References pool, and readGraph().
Graph::~Graph (void)
Definition at line 15 of file Graph.cpp.
References nodeArray, pool, and prevArray.
Member Function Documentation
int Graph::getSource () [inline]
Definition at line 18 of file Graph.h.
References sourceID.
Referenced by PushRelabel::calc(), PushRelabel::dijkstraPath(), PushRelabel::discharge(), PushRelabel::discharge_back(), and PushRelabel::updateLabels().
int Graph::getTarget () [inline]
Definition at line 19 of file Graph.h.
References targetID.
Referenced by PushRelabel::calc(), PushRelabel::dijkstraPath(), PushRelabel::discharge(), and PushRelabel::updateLabels().
int Graph::getNodesNum () [inline]
Definition at line 20 of file Graph.h.
References nodesNum.
Referenced by PushRelabel::calc(), PushRelabel::dijkstraPath(), PushRelabel::flow(), and PushRelabel::updateLabels().
int Graph::getEdgesNum () [inline]
Definition at line 21 of file Graph.h.
References edgesNum.
int Graph::getMaxDistance () [inline]
Definition at line 22 of file Graph.h.
References maxDistance.
void Graph::setMaxDistance (int max) [inline]
Definition at line 23 of file Graph.h.
References maxDistance.
Referenced by PushRelabel::updateLabels().
NodePool* Graph::getPool () [inline]
Definition at line 25 of file Graph.h.
References pool.
Referenced by PushRelabel::calc(), PushRelabel::discharge(), PushRelabel::discharge_back(), PushRelabel::flow(), and PushRelabel::preflow().
int Graph::readGraph (string file)
Definition at line 24 of file Graph.cpp.
References Node::addEdge(), DEBUG, edgesNum, LOG_1, LOG_3, nodeArray, nodesNum, prevArray, EdgeEntry::setReversed(), sourceID, and targetID.
Referenced by Graph().
int Graph::printGraph ()
Definition at line 267 of file Graph.cpp.
References nodeArray, nodesNum, Node::printNode(), sourceID, and targetID.
Referenced by PushRelabel::calc().
int Graph::debugDump ()
Definition at line 284 of file Graph.cpp.
References Node::debugNodeDump(), nodeArray, nodesNum, sourceID, and targetID.
Referenced by PushRelabel::calc().
Node* Graph::getNodeArray () [inline]
Definition at line 30 of file Graph.h.
References nodeArray.
Referenced by PushRelabel::calc().
int Graph::dijkstra (int source_id, int *& dist, int *& prev, int & max)
Definition at line 169 of file Graph.cpp.
References DijkstraQueue::addNode(), Node::getAdjList(), EdgeEntry::getEndPoint(), EdgeEntry::getFlow(), Node::getID(), EdgeEntry::getNext(), DijkstraQueue::getNode(), EdgeEntry::getResCapacity(), INFINITY, NodePool::isEmpty(), EdgeEntry::isReverseEdge(), nodeArray, nodesNum, pool, prevArray, sourceID, and targetID.
Referenced by PushRelabel::dijkstraPath().
int Graph::incPrevPathCap (int val)
Definition at line 298 of file Graph.cpp.
References Node::getAdjList(), EdgeEntry::getEndPoint(), EdgeEntry::getNext(), EdgeEntry::getReverse(), EdgeEntry::incCapacity(), nodeArray, prevArray, sourceID, and targetID.
Referenced by main().
Member Data Documentation
int* Graph::prevArray
Definition at line 34 of file Graph.h.
Referenced by dijkstra(), incPrevPathCap(), readGraph(), PushRelabel::updateLabels(), and ~Graph().
int Graph::sourceID [private]
Definition at line 38 of file Graph.h.
Referenced by debugDump(), dijkstra(), getSource(), incPrevPathCap(), printGraph(), and readGraph().
int Graph::targetID [private]
Definition at line 39 of file Graph.h.
Referenced by debugDump(), dijkstra(), getTarget(), incPrevPathCap(), printGraph(), and readGraph().
int Graph::nodesNum [private]
Definition at line 40 of file Graph.h.
Referenced by debugDump(), dijkstra(), getNodesNum(), printGraph(), and readGraph().
int Graph::edgesNum [private]
Definition at line 41 of file Graph.h.
Referenced by getEdgesNum(), and readGraph().
int Graph::maxDistance [private]
Definition at line 42 of file Graph.h.
Referenced by getMaxDistance(), and setMaxDistance().
NodePool* Graph::pool [private]
Definition at line 43 of file Graph.h.
Referenced by dijkstra(), getPool(), Graph(), and ~Graph().
Node* Graph::nodeArray [private]
Definition at line 44 of file Graph.h.
Referenced by debugDump(), dijkstra(), getNodeArray(), incPrevPathCap(), printGraph(), readGraph(), and ~Graph().
The documentation for this class was generated from the following files:
C:/Users/Nimrod/Documents/University/2007 - Semester 1/Algorithm Workshop/Project/Graph.h
C:/Users/Nimrod/Documents/University/2007 - Semester 1/Algorithm Workshop/Project/Graph.cpp